### ISSUE TITLE
Build failed on Windows, use Visual C++ 2013~2015

### ISSUE THREAD

**Issue by fcharlie** [jen20/libuv-cmake#3]
In https://github.com/jen20/libuv-cmake/blob/aaf15114968f6cab626fc78f35a53d20b71312d2/CMakeLists.txt#L28

Override **winsock.h** , should comment this line.

**Comment by jen20** [comment]
:+1: I'll fix that up over the weekend when I get a chance. I've only ever tested this with mingw - is that the only blocker for VS compatibility?

**Comment by fcharlie** [comment]
This problem also occurs in the MSYS2-MinGW64

> mkdir build &&cmake -G"MSYS Makefiles" .. && make

![01](https://cloud.githubusercontent.com/assets/6904176/17074235/efde1b82-50ab-11e6-9012-1e76e62c8c55.JPG)

After comment this line:

![02](https://cloud.githubusercontent.com/assets/6904176/17074245/fbe4b81e-50ab-11e6-9867-a7f2abc13e6b.JPG)

**Comment by smasherprog** [comment]
The PR I just submitted should have fixed this issue. Please double check though.
